name: Flask CI

on:
  push:
    branches: [Feature-tests]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: use python
        uses: actions/setup-python@v2

      - run: pip install -r requirements.txt
      - run: python app_test.py